### ISSUE TITLE
make unsafe-free but leaky version

### ISSUE THREAD

**Issue by josharian** [go4org/intern#3]
If people suspect a bug in package intern—which of course is impossible—it’d be nice for them to be able to set a build tag that switches to safe-but-leaky, with unchanged API and semantics.

If no one beats me to it I can do this tomorrow.

build tag bike shed color opinions?

cc @danderson

**Comment by bradfitz** [comment]
Or an environment variable, like https://github.com/go4org/intern/pull/6 ?
